### ISSUE TITLE
Incorrect types for Id members in DTO structs breaks various APIs

### ISSUE THREAD

**Issue by gplusplus314** [grokify/go-ringcentral-client#17]
The `GetMessageInfoResponse` and `MessageAttachmentInfo` structs have a member named `Id` of type `string`. Normally, this would be okay, but a Number type is sent by the APIs (that is, no quotes around the value) in the JSON, so the marshaller is expecting to assign the value to a numeric type.

Changing the type from `string` to `json.Number` fixes the issue. This allows the underlying type to still be a string, but the marshaller will be able to assign it a numeric value.

This bug breaks _at least_ the following APIs:
- `SyncMessage`
- `GetMessageList`
- ... probably other things that fetch messages or attachments.

**Comment by grokify** [comment]
`GetMessageInfoResponse` and `MessageAttachmentInfo` are referenced in multiple endpoints and definitions. The RingCentral API uses both strings and int64 integers for ids. The forward direction is to use strings for all ids however a number of endpoints still use integers. An important consideration is that sometimes the same definition is referenced by two APIs, one returning a string and another an integer.

This is the case with `MessageAttachmentInfo` where the following endpoints/definitions use different id types:

| type | endpoint or definition |
|-------|--------------------------|
| integer | `GET /restapi/v1.0/account/{accountId}/extension/{extensionId}/message-store` returns `GetMessageList` with an array of `GetMessageInfoResponse` |
| string | `InstantMessageEvent` |

The current approach is to split into two definitions, with one ending in `IntId` such as `MessageAttachmentInfoIntId`. The reason for this is to continue to rely on Swagger spec types and Swagger codegen. This was previously added in 526e506dafbd552684e5d7849ea26c869a451f93 . It's worth experimenting with `json.Number` to see if it can transparently handle both.

For reference, these two definitions appear in the following endpoints and definitions:

`GetMessageInfoResponse` is referenced in the following definitions:

* `POST /restapi/v1.0/account/{accountId}/extension/{extensionId}/sms`
* `POST /restapi/v1.0/account/{accountId}/extension/{extensionId}/company-pager`
* `GET /restapi/v1.0/account/{accountId}/extension/{extensionId}/message-store/{messageId}`
* `PUT /restapi/v1.0/account/{accountId}/extension/{extensionId}/message-store/{messageId}`
* `GetMessageList`
* `GetMessageSyncResponse`

`MessageAttachmentInfo` is referenced in the following definitions:

* `GetMessageInfoResponse`
* `MessageInfoResource`
* `InstantMessageEvent` - [example_event_instant_message_sms.json](https://github.com/grokify/go-ringcentral/blob/master/clientutil/example_event_instant_message_sms.json) (string)

**Comment by grokify** [comment]
Using the `json.Number` type is interesting because it can parse both JSON strings and numbers transparently. Converting to JSON would always result in a number, but that might be okay if the definitions are not used in any requests. This also means more changes for Swagger Codgen or post-processing.

That being said, we want the Swagger spec = to be entirely correct so that these models will be updated to use `format: "int64"`.

**Comment by grokify** [comment]
* `GetMessageList ` API fixed in 082db6a62db662c4201a7b03e5d5330e24f0a625 via Swagger spec update.

**Comment by grokify** [comment]
Closing this now since it's been resolved with additional types. Feel free to reopen if other other instances occur.

For `json.Number` I'm looking into getting support with OpenAPI Generator. It seems pretty easy to add but worth a discussion. Please post there to voice your thoughts there.

https://github.com/OpenAPITools/openapi-generator/issues/501
