### ISSUE TITLE
parameterToString() incorrectly encodes time.Time

### ISSUE THREAD

**Issue by kninan** [grokify/go-ringcentral-client#33]
In `client/client.go` the function `parameterToString()` returns incorrectly encoded query parameter values for `time.Time` interfaces. Before the latest update:

```go
if reflect.TypeOf(obj).Kind() == reflect.Slice {
	return strings.Trim(strings.Replace(fmt.Sprint(obj), " ", delimiter, -1), "[]")
} else if t, ok := obj.(time.Time); ok {
	return t.Format(time.RFC3339)
}
```

This worked but the function now reads 

```go
if reflect.TypeOf(obj).Kind() == reflect.Slice {
	return strings.Trim(strings.Replace(fmt.Sprint(obj), " ", delimiter, -1), "[]")
} 
```

and returns 400 bad request status code

**Comment by grokify** [comment]
Sorry about that. It's been fixed in 1304dfedf99e9430ba3c99bda7c3bc9b26ab30bc

Previously, I was patching it locally and had contributed a PR to the [OpenAPI Generator](https://github.com/OpenAPITools/openapi-generator) project which should have included it in 3.1.0:

https://github.com/OpenAPITools/openapi-generator/pull/502
